" Default values for every g:org_* variable.
" ── DO NOT edit this file. ──────────────────────────────────────────────────
" Put your personalisation in ~/.vim/after/plugin/org_user.vim
" (copy config/user.vim from this repo as a starting template).
" Variables already set before this file loads are left untouched.

" Keyword sequence.  Two formats are accepted:
"   flat:   ['TODO', 'NEXT', '|', 'DONE', 'CANCELLED']
"   nested: [['TODO', 'NEXT'], ['DONE', 'CANCELLED']]
" Keywords before '|' (or in list 0) are active/pending.
" Keywords after  '|' (or in list 1) are done/finished.
if !exists('g:org_todo_keywords')
  let g:org_todo_keywords = ['TODO', 'NEXT', 'WAITING', '|', 'DONE', 'CANCELLED']
endif

" Per-keyword colour overrides.
" Keys are keyword strings; values are either:
"   • a raw :highlight spec  'ctermfg=196 cterm=bold guifg=#fb4934 gui=bold'
"   • an existing group name 'Comment'
" Keywords not listed here get a colour from the built-in ramp automatically.
if !exists('g:org_todo_keyword_faces')
  let g:org_todo_keyword_faces = {}
endif

" Agenda: list of .org file paths OR directory paths to scan.
" A directory entry expands to all *.org files directly inside it.
" Empty list (default) → falls back to the current buffer when it is an org file.
" Example: let g:org_agenda_files = ['E:\org']
if !exists('g:org_agenda_files')
  let g:org_agenda_files = []
endif

" Agenda: number of days ahead to show in the Deadlines view.
if !exists('g:org_agenda_deadline_days')
  let g:org_agenda_deadline_days = 14
endif

" Agenda: height of the horizontal split opened by :OrgAgenda.
if !exists('g:org_agenda_window_height')
  let g:org_agenda_window_height = 20
endif

" Show past-due SCHEDULED items on today until they are marked done, the way
" Emacs org-agenda does ('Sched.Nx' = N days since the missed occurrence).
" Set to 0 to list a repeating task only on its exact occurrence dates.
if !exists('g:org_agenda_show_past_scheduled')
  let g:org_agenda_show_past_scheduled = 1
endif

" Agenda day view: first and last hour shown in the timeline (24-hour clock).
if !exists('g:org_agenda_day_start')
  let g:org_agenda_day_start = 7
endif
if !exists('g:org_agenda_day_end')
  let g:org_agenda_day_end = 22
endif
